name: widgets_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  animate_do: ^4.1.1
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  go_router: ^14.8.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon_library_design.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true

  assets:
    - assets/images/